### ISSUE TITLE
Error while running "mvn clean install exec:java"

### ISSUE THREAD

**Issue by jzelez** [neo4j-contrib/rabbithole#46]
Hi. I'm having trouble building from source. Can you help ?

```
Failed tests: 
  testNoUpdate(org.neo4j.community.console.QueryStatisticsTest): time

Tests run: 52, Failures: 1, Errors: 0, Skipped: 1

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.883s
[INFO] Finished at: Tue Jan 08 17:54:23 CET 2013
[INFO] Final Memory: 15M/81M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.7.2:test (default-test) on project rabbithole: There are test failures.
```

**Comment by sampathkadava123** [comment]
please help me to solve this problem

[INFO]
[INFO] --- exec-maven-plugin:1.4.0:java (default-cli) @ edi_to_java ---
[WARNING]
java.lang.ClassNotFoundException: src.test.java.org.smooksam.edi_to_java.AppTest
.java
        at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:281)
        at java.lang.Thread.run(Thread.java:745)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.158 s
[INFO] Finished at: 2016-03-10T16:29:41+05:30
[INFO] Final Memory: 9M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.4.0:java (d
efault-cli) on project edi_to_java: An exception occured while executing the Jav
a class. src.test.java.org.smooksam.edi_to_java.AppTest.java -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionE
xception

C:\Users\102878\workspace\edi_to_java>
